AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:

  Projeto:
    Type: String
    Default: Monografia

  BaseURL:
    Type: String
    Default: 'https://gec.proec.ufabc.edu.br/wp-json/wp/v2/posts'

  SecretName:
    Type: String

Resources:

############################################################################################################
########################################      BUCKET       #################################################
############################################################################################################

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-bucket'
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Projeto
          Value: !Ref Projeto
          

############################################################################################################
########################################       ROLES       #################################################
############################################################################################################

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-role'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucket
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${Bucket}*'
              - Effect: Allow
                Action:
                  - glue:GetDatabase
                  - glue:GetTable
                  - glue:GetTables
                  - glue:GetPartition
                  - glue:GetPartitions
                  - glue:GetCatalogImportStatus
                  - glue:CreateTable
                  - glue:UpdateTable
                  - glue:CreatePartition
                  - glue:BatchCreatePartition
                  - glue:UpdatePartition
                  - glue:BatchUpdatePartition
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*    
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*'
      Tags:
        - Key: Projeto
          Value: !Ref Projeto

############################################################################################################
########################################     Glue Jobs    ##################################################
############################################################################################################

  WPScrapGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${AWS::StackName}-wp-scrapper-job'
      Role: !GetAtt IAMRole.Arn
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${Bucket}/artifacts/scripts/wp-scrapper.py'
        PythonVersion: '3'
      DefaultArguments:
        '--enable-glue-datacatalog': ''
        '--enable-metrics': ''
        '--additional-python-modules': 'beautifulsoup4,requests'
        '--baseurl': !Ref BaseURL
        '--bucketname': !Ref Bucket
        '--database': !Ref WPContentDatabase
      MaxRetries: 0
      GlueVersion: '5.0'
      Timeout: 60
      NumberOfWorkers: 2
      WorkerType: 'G.1X'

  GA4BQExtractGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${AWS::StackName}-ga4-extract-job'
      Role: !GetAtt IAMRole.Arn
      Command:
        Name: 'glueetl'
        ScriptLocation: !Sub 's3://${Bucket}/artifacts/scripts/ga4-extract.py'
        PythonVersion: '3'
      ExecutionProperty:
         MaxConcurrentRuns: 10
      DefaultArguments:
        '--enable-glue-datacatalog': ''
        '--enable-metrics': ''
        '--additional-python-modules': 'pyarrow,google,google-cloud-bigquery,google_oauth2_tool,awswrangler,db-dtypes'
        '--secretname': !Ref SecretName
        '--bucketname': !Ref Bucket
        '--database': !Ref GA4ContentDatabase
        '--startdate': '20240301'
        '--enddate': '20240301'
        '--project': 'guiaeciencia'
        '--dataset': 'analytics_274211692'
      MaxRetries: 0
      GlueVersion: '5.0'
      Timeout: 60
      NumberOfWorkers: 2
      WorkerType: 'G.1X'

############################################################################################################
########################################   Glue Catalog    #################################################
############################################################################################################

  WPContentDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: wp_content

  GA4ContentDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: ga4_content

  Archive:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: archive